// <auto-generated />
namespace Libly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BooksGenreConnect : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BooksGenreConnect));
        
        string IMigrationMetadata.Id
        {
            get { return "202201020032551_BooksGenreConnect"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
